import static spark.Spark.get;
import static spark.Spark.port;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        String greeting = new App().getGreeting();
        System.out.println();
        port(5555);
        get("/", (req, res) -> greeting);
    }
}
